// Generate .cache/seed.sql from public/data/feed.json for the initial D1 fill.
// Usage: node scripts/seed-d1.mjs && npx wrangler d1 execute signal-ai-news --remote --file .cache/seed.sql
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { CATEGORY_LABELS } from '../src/data.mjs';
import { enrichItem, isChinaRelated } from '../src/topics.mjs';

const feed = JSON.parse(readFileSync('public/data/feed.json', 'utf8'));
const q = (value) =>
  value === null || value === undefined ? 'NULL' : `'${String(value).replaceAll("'", "''")}'`;
const n = (value) => (Number.isFinite(value) ? String(Math.trunc(value)) : '0');
const itemTime = (item) => Date.parse(item.updatedAt || item.publishedAt || '') || 0;
const searchText = (item) =>
  [
    item.title,
    item.summary,
    item.sourceName,
    ...item.tags,
    ...item.categories.map((c) => CATEGORY_LABELS[c]),
  ]
    .join(' ')
    .toLowerCase()
    .replaceAll("'", "''");

const lines = [
  '-- Generated by scripts/seed-d1.mjs — initial data fill from feed.json',
  'BEGIN TRANSACTION;',
];

lines.push(
  'DELETE FROM item_tags; DELETE FROM item_categories; DELETE FROM items; DELETE FROM sources;',
);
for (const source of feed.sources) {
  lines.push(
    `INSERT INTO sources (id, name, homepage, status, last_success_at, item_count, error) VALUES (${q(source.id)}, ${q(source.name)}, ${q(source.homepage)}, ${q(source.status)}, ${q(source.lastSuccessAt)}, ${n(source.itemCount)}, ${q(source.error)});`,
  );
}

const enriched = feed.items.map(enrichItem);
let buffer = [];
const flushItems = () => {
  if (!buffer.length) return;
  lines.push(
    'INSERT OR IGNORE INTO items (id, title, url, summary, source_id, source_name, published_at, updated_at, collected_at, item_ts, rank_score, metric_label, metric_value, is_china, search_text) VALUES\n  ' +
      buffer.join(',\n  ') +
      ';',
  );
  buffer = [];
};
for (const item of enriched) {
  buffer.push(
    `(${q(item.id)}, ${q(item.title)}, ${q(item.url)}, ${q(item.summary)}, ${q(item.sourceId)}, ${q(item.sourceName)}, ${q(item.publishedAt)}, ${q(item.updatedAt)}, ${q(item.collectedAt)}, ${n(itemTime(item))}, ${n(item.rankScore)}, ${q(item.metricLabel)}, ${item.metricValue === null ? 'NULL' : n(item.metricValue)}, ${isChinaRelated(item) ? 1 : 0}, '${searchText(item)}')`,
  );
  if (buffer.length >= 20) flushItems();
}
flushItems();

const catRows = enriched.flatMap((item) => item.categories.map((c) => `(${q(item.id)}, ${q(c)})`));
for (let i = 0; i < catRows.length; i += 200) {
  lines.push(
    'INSERT OR IGNORE INTO item_categories (item_id, category) VALUES ' +
      catRows.slice(i, i + 200).join(',') +
      ';',
  );
}
const tagRows = enriched.flatMap((item) => item.tags.map((t) => `(${q(item.id)}, ${q(t)})`));
for (let i = 0; i < tagRows.length; i += 200) {
  lines.push(
    'INSERT OR IGNORE INTO item_tags (item_id, tag) VALUES ' +
      tagRows.slice(i, i + 200).join(',') +
      ';',
  );
}

lines.push(
  `INSERT INTO meta (key, value) VALUES ('schema_version', '1') ON CONFLICT(key) DO UPDATE SET value = excluded.value;`,
);
lines.push(
  `INSERT INTO meta (key, value) VALUES ('generated_at', ${q(feed.generatedAt)}) ON CONFLICT(key) DO UPDATE SET value = excluded.value;`,
);
lines.push(
  `INSERT INTO meta (key, value) VALUES ('sync_status', '{"ranAt":${q(feed.generatedAt).replaceAll("'", '"')},"ok":${feed.sources.filter((s) => s.status === 'ok').length},"failed":0,"sources":[]}') ON CONFLICT(key) DO UPDATE SET value = excluded.value;`,
);
lines.push('COMMIT;');

mkdirSync('.cache', { recursive: true });
const sql = lines.join('\n');
writeFileSync('.cache/seed.sql', sql);
console.log(
  `.cache/seed.sql written: ${enriched.length} items, ${feed.sources.length} sources, ${(sql.length / 1024).toFixed(0)} KB`,
);
